<?php
/* @var Select $block */
/* @var CustomProduct $viewModel */
/* @var Escaper $escaper */

use Ls\Hospitality\ViewModel\CustomProduct;
use Magento\Catalog\Api\Data\ProductCustomOptionInterface;
use Magento\Catalog\Block\Product\View\Options\Type\Select;
use Magento\Framework\Escaper;

?>
<?php
$_option   = $block->getOption();
$class     = ($_option->getIsRequire()) ? ' required' : '';
$viewModel = $block->getData('view_model');
$criteria  = $viewModel->isHospitalityStore() && $viewModel->currentProductHasOptions();
if ($criteria) {
    $_option = $viewModel->checkModifierAvailable($_option);
}
?>
<div class="<?= $criteria ? 'custom-field ' : '' ?>field<?= $escaper->escapeHtmlAttr($class) ?>">
    <label class="label" for="select_<?= $escaper->escapeHtmlAttr($_option->getId()) ?>">
        <span><?= $escaper->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?= $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()) : ?>
            <?php if ($_option->getType() == ProductCustomOptionInterface::OPTION_TYPE_RADIO ||
                    $_option->getType() == ProductCustomOptionInterface::OPTION_TYPE_CHECKBOX
            ) : ?>
                <span id="options-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>-container"></span>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($criteria) : ?>
            <div class="custom-container">
                <div class="custom-option-container">
                    <div class="image-container">
                        <img class="notlazy" src="<?= $viewModel->getMediaUrl($_option->getSwatch()) ?>"
                             alt="<?= $escaper->escapeHtml($_option->getTitle()) ?>"/>
                    </div>
                    <p class="title"><?= $escaper->escapeHtml($_option->getTitle()) ?></p>
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                </div>
                <div class="custom-option-values-container<?= $_option->getType() == 'multiple' ? ' multiselect' : '' ?>"
                     data-ls_modifer_recipe_id="<?= $escaper->escapeHtmlAttr($_option->getLsModifierRecipeId()) ?>"
                     data-custom-option-id="options[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                     style="display:none;">
                    <ul>
                        <li class="option default"><?= $escaper->escapeHtml(__('-- Please Select --')) ?></li>
                        <?php foreach ($_option->getValues() as $val) : ?>
                            <?php
                            $isAvailable = isset($val['is_available']) ? $val['is_available'] : true;
                            $title = $escaper->escapeHtml($val->getTitle());
                            ?>
                            <li class="option<?= !$isAvailable ? ' unavailable' : '' ?>"
                                data-custom-value-id="<?= $escaper->escapeHtmlAttr($val->getOptionTypeId()) ?>"
                                data-available="<?= $isAvailable ? 'true' : 'false' ?>">
                                <div class="image-container">
                                    <img class="notlazy" src="<?= $viewModel->getMediaUrl($val->getSwatch()) ?>"
                                         alt="<?= $title ?>"/>
                                </div>
                                <p class="title"><?= $title ?></p>
                                <p class="title2"><?= !$isAvailable ? '<span class="sold-out-label">' . $escaper->escapeHtml(__('Out of Stock')) . '</span>' : '' ?></p>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
