<?php
/**
 * For loading sales type
 *
 * @var \Ls\Hospitality\Block\Adminhtml\System\Config\SalesType $block
 * @var \Magento\Framework\Escaper $escaper
 */
$ajaxUrl = $block->getAjaxUrl();
?>
<script type="text/x-magento-init">
{
    "*": {
        "loadsalestype": {
            "ajaxUrl": "<?= $escaper->escapeUrl($ajaxUrl) ?>",
            "websiteId": "<?= $block->getWebsiteId(); ?>"
        }
    }
}

</script>
