<?php
/** @var  \Ls\Customer\Block\Order\Info $block */

list($status, $estimatedTime) = $block->getData('data');
if (empty($status)) {
    $status = __('Kitchen status service is down. Please try again by refreshing the page.');
}
?>
<div class="hosp-info-container">
    <div class="block-content">
        <div class="custom-box">
            <strong class="box-title"><span><?= /* @escapeNotVerified */__('Status:') ?></span></strong>
            <span><?= /* @escapeNotVerified */ $status; ?></span>
        </div>
    </div>
    <?php if ($estimatedTime > 0): ?>
        <div class="block-content">
            <div class="custom-box">
                <strong class="box-title"><span>
                <?= /* @escapeNotVerified */__('Estimated Time:') ?></span></strong>
                <span><?= /* @escapeNotVerified */ $estimatedTime; ?> <?= /* @escapeNotVerified */__('Minutes') ?></span>
            </div>
        </div>
    <?php endif; ?>
</div>
