<?php
/** @var  Ls\Customer\Block\Order\Info|Magento\Framework\View\Element\Template $block */
/** @var  Ls\Hospitality\ViewModel\CustomerOrderInfo $viewModel */

$viewModel = $block->getData("view_model");
if ($viewModel->isHospitalityEnabled() == "1") :
    $ajaxUrl         = $block->getUrl('hospitality/ajax/OrderInfo');
    $statusInfo      = $viewModel->getOrderStatusInfo();
    $order           = $block->getOrder();
    $magOrder        = $block->getMagOrder();
    $orderId         = null;
    $pickupOrderTime = '';
    $orderComment    = '';
    $storeId         = '';
    if (!empty($statusInfo)) {
        $orderId         = $statusInfo['orderId'];
        $storeId         = $statusInfo['storeId'];
        $pickupOrderTime = $statusInfo['pickupDateTimeslot'];
    }

    if (!empty($order)) {
        $orderId = $order->getId();
        $storeId = $order->getStoreId();
    }
    if (!empty($magOrder)) {
        $pickupOrderTime = $magOrder->getPickupDateTimeslot();
        $orderComment    = $magOrder->getLsOrderComment();
    }
    if ($orderId):
        ?>
        <div class="block block-order-details-view-loyalty ls-kitchen-order-status">
            <div class="block-title">
                <strong><?= /* @escapeNotVerified */
                    __('Kitchen Information') ?></strong>
            </div>
            <div id="ls-hosp-order-info">
                <div class="loader">
                    <img src="<?= /* @escapeNotVerified */
                    $block->getViewFileUrl('images/loader-1.gif') ?>"
                         alt="<?= /* @escapeNotVerified */
                         __('Loading...') ?>">
                    <br/>
                    <div><?php echo __('Loading Kitchen Info...'); ?></div>
                </div>
            </div>
        </div>
        <script type="text/x-magento-init">
        {
            "*": {
                "Ls_Hospitality/js/view/customer/order/info": {
                    "ajaxUrl": "<?php echo $ajaxUrl; ?>",
                    "orderId": "<?php echo $orderId; ?>",
                    "storeId": "<?php echo $storeId; ?>",
                    "pickupOrderTime":"<?php echo $pickupOrderTime; ?>"
                }
            }
        }





        </script>

        <?php if ($orderComment): ?>
        <div class="block block-order-details-view-loyalty">
            <div class="block-title">
                <strong><?= /* @escapeNotVerified */
                    __('Additional Information') ?></strong>
            </div>
            <div class="block-content">
                <div class="custom-box">
                    <span><?= /* @escapeNotVerified */
                        $orderComment; ?></span>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
